// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9ce0ITEoFqHZzLY0b9I6LmiQ3_3MHZMM',
    appId: '1:1043442348983:web:d8b007db66a520caecae32',
    messagingSenderId: '1043442348983',
    projectId: 'emudeck-a354d',
    authDomain: 'emudeck-a354d.firebaseapp.com',
    storageBucket: 'emudeck-a354d.appspot.com',
    measurementId: 'G-BGDW849J8X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnCvJQH9jed2_S1cJLru96Xy4OTZaT7l8',
    appId: '1:1043442348983:android:578e3f651044574eecae32',
    messagingSenderId: '1043442348983',
    projectId: 'emudeck-a354d',
    storageBucket: 'emudeck-a354d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgUmnR0geaqQRlOUdN10cqhwsmhfg_hHc',
    appId: '1:1043442348983:ios:e8f09db39d9c9bddecae32',
    messagingSenderId: '1043442348983',
    projectId: 'emudeck-a354d',
    storageBucket: 'emudeck-a354d.appspot.com',
    iosClientId: '1043442348983-51gd2om9p0limm3vhpgdqcl9kb6915ha.apps.googleusercontent.com',
    iosBundleId: 'com.example.emudeck',
  );
}
